apiVersion: apps/v1 
kind: Deployment
metadata:
  name: autoscale-app
spec: 
  selector:
    matchLabels:
      app: autoscale
      env: capstone-blue
  replicas: 2
  template:
    metadata:
      labels:
        app: autoscale
        env: capstone-blue
    spec:
      containers:
      - name: nodejs-loop
        image: 210700574655.dkr.ecr.us-east-1.amazonaws.com/capstone-eventweb:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"


